version: '3.3'

services:
  kafka:
    image: wurstmeister/kafka
    environment:
      HOSTNAME_COMMAND: "hostname -i"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://_{HOSTNAME_COMMAND}:9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: on-failure
    volumes:
      - kafka_data:/kafka
    depends_on:
      - zookeeper
    networks:
      - kafka

  # Kafka requires Zookeper
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - kafka

  helloworld:
    image: docker-springboot-kafka:latest
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
    depends_on:
      - kafka
    restart: always
    networks:
      - kafka

volumes:
  kafka_data:

networks:
  default:
  kafka: